# version: '3.9' # optional

services:

  api:
    image: ocr_api
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT_DOCKER}"
    volumes:
    - .:/code
    depends_on:
      - migration_app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${API_PORT_DOCKER}", "--reload"]


  migration_app:
    container_name: migration_app
    build: .
    # image: continuumio/miniconda
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    command: "alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy


  db:
    image: mysql
    restart: unless-stopped
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      -  mysql_data:/var/lib/mysql
      - ./db_data/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -P 3306 -p${DB_PASSWORD} | grep 'mysqld is alive' || exit 1"]


  adminer:
    container_name: adminer_ocr_api
    image: adminer
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080


volumes:
  mysql_data: