# version: '3.9' # optional

services:

  api:
    links:
      - db
    container_name: api
    build: .
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT_DOCKER}"
    volumes:
    - .:/code
    networks:
      - local-net
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${API_PORT_DOCKER}", "--reload"]


  db:
    image: mysql
    restart: unless-stopped
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      -  mysql_data:/var/lib/mysql
    networks:
      - local-net


  adminer:
    container_name: adminer_ocr_api
    image: adminer
    depends_on:
      - db
    links:
      - db:db
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - local-net


volumes:
  mysql_data:


networks:
  local-net:
    driver: bridge