# version: '3.9' # optional

services:

  api:
    links:
      - db
    container_name: api
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
    - .:/code
    networks:
      - local-net
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - HASH_ALGORITHM=${HASH_ALGORITHM}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - API_PORT=${API_PORT}
      - DB_PORT=${DB_PORT}
      - APP_DATABASE=${APP_DATABASE}
      - DB_DOCKER_SERVICE=${DB_DOCKER_SERVICE}
      - DB_DRIVER=${DB_DRIVER}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}


  db:
    image: mysql
    restart: unless-stopped
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "3306:3306"
    volumes:
      -  mysql_data:/var/lib/mysql
    networks:
      - local-net


  adminer:
    container_name: adminer_ocr_api
    image: adminer
    depends_on:
      - db
    links:
      - db:db
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - local-net


volumes:
  mysql_data:


networks:
  local-net:
    driver: bridge