# version: '3.9' # optional

services:

  api_gateway:
    image: api_gateway
    build: .
    container_name: api_gateway
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT_DOCKER}"
    volumes:
    - .:/code
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${API_PORT_DOCKER}", "--reload"]