# version: '3.9' # optional

services:

  api:
    image: ocr_api
    build: .
    container_name: ocr_api
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT_DOCKER}"
    volumes:
    - .:/code
    depends_on:
      - migration_app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${API_PORT_DOCKER}", "--reload"]


  migration_app:
    container_name: migration_app
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    command: "alembic upgrade head"


  redis:
    image: redis:6.2-alpine
    container_name: redis


  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_tasks.celery worker --loglevel=info --pool=solo
    volumes:
      - .:/code
    depends_on:
      - api
      - redis


  flower:
    container_name: flower
    build: .
    command: celery -A celery_tasks.celery flower --port=5555
    ports:
      - ${FLOWER_PORT}:5555
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_URL=${CELERY_BROKER_URL}
    depends_on:
      - api
      - redis
      - celery_worker