"""empty message

Revision ID: 92b7ae7b9dd6
Revises: d9f1568e651c
Create Date: 2022-07-06 11:23:47.914761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92b7ae7b9dd6'
down_revision = 'd9f1568e651c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_results', sa.Column('_result', sa.Text(), nullable=False))
    op.drop_column('file_results', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_results', sa.Column('result', mysql.TEXT(), nullable=False))
    op.drop_column('file_results', '_result')
    # ### end Alembic commands ###
