"""empty message

Revision ID: a955928ea1e8
Revises: 92b7ae7b9dd6
Create Date: 2022-07-06 11:27:17.863507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a955928ea1e8'
down_revision = '92b7ae7b9dd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_results', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_results', 'created_date')
    # ### end Alembic commands ###
