"""empty message

Revision ID: d9f1568e651c
Revises: a69521078ee9
Create Date: 2022-07-06 11:02:37.898913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9f1568e651c'
down_revision = 'a69521078ee9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_results', sa.Column('result', sa.Text(), nullable=False))
    op.drop_column('file_results', 'result_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_results', sa.Column('result_text', mysql.TEXT(), nullable=False))
    op.drop_column('file_results', 'result')
    # ### end Alembic commands ###
