"""empty message

Revision ID: 00a9a21dd0a3
Revises: f282020510e1
Create Date: 2022-07-21 08:19:07.051985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a9a21dd0a3'
down_revision = 'f282020510e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
