"""empty message

Revision ID: 3ff237b7c1ce
Revises: 968cd4242ccc
Create Date: 2022-07-21 12:24:58.885503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff237b7c1ce'
down_revision = '968cd4242ccc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('frames_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'frames_count')
    # ### end Alembic commands ###
