"""empty message

Revision ID: 4827b221da5a
Revises: f97a8a834e51
Create Date: 2022-07-21 08:12:12.640170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4827b221da5a'
down_revision = 'f97a8a834e51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('is_scanned', sa.Boolean(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_results_id'), 'image_results', ['id'], unique=False)
    op.drop_index('taskset_id', table_name='celery_tasksetmeta')
    op.drop_table('celery_tasksetmeta')
    op.drop_index('ix_file_results_id', table_name='file_results')
    op.drop_table('file_results')
    op.drop_index('task_id', table_name='celery_taskmeta')
    op.drop_table('celery_taskmeta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_taskmeta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('date_done', mysql.DATETIME(), nullable=True),
    sa.Column('traceback', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('args', sa.BLOB(), nullable=True),
    sa.Column('kwargs', sa.BLOB(), nullable=True),
    sa.Column('worker', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('retries', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue', mysql.VARCHAR(length=155), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('task_id', 'celery_taskmeta', ['task_id'], unique=False)
    op.create_table('file_results',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('result', mysql.TEXT(), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_scanned', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='file_results_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_file_results_id', 'file_results', ['id'], unique=False)
    op.create_table('celery_tasksetmeta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('taskset_id', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('date_done', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('taskset_id', 'celery_tasksetmeta', ['taskset_id'], unique=False)
    op.drop_index(op.f('ix_image_results_id'), table_name='image_results')
    op.drop_table('image_results')
    # ### end Alembic commands ###
