"""empty message

Revision ID: 4a1e7eb48df4
Revises: 
Create Date: 2022-07-14 10:08:19.088172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1e7eb48df4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_results', sa.Column('is_scanned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_results', 'is_scanned')
    # ### end Alembic commands ###
