"""empty message

Revision ID: 4cdb655a116e
Revises: 00a9a21dd0a3
Create Date: 2022-07-21 09:49:36.000421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdb655a116e'
down_revision = '00a9a21dd0a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
