"""empty message

Revision ID: 74b69b256a2e
Revises: 3ff237b7c1ce
Create Date: 2022-07-21 13:25:11.867010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b69b256a2e'
down_revision = '3ff237b7c1ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
