"""empty message

Revision ID: 968cd4242ccc
Revises: b650330e449a
Create Date: 2022-07-21 11:21:35.644038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968cd4242ccc'
down_revision = 'b650330e449a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_results', sa.Column('video_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image_results', 'videos', ['video_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_results', type_='foreignkey')
    op.drop_column('image_results', 'video_id')
    # ### end Alembic commands ###
