"""empty message

Revision ID: b650330e449a
Revises: de16bf7d894a
Create Date: 2022-07-21 10:12:08.945616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b650330e449a'
down_revision = 'de16bf7d894a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_results', sa.Column('video_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'image_results', 'videos', ['video_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_results', type_='foreignkey')
    op.drop_column('image_results', 'video_id')
    # ### end Alembic commands ###
