"""empty message

Revision ID: f97a8a834e51
Revises: 4a1e7eb48df4
Create Date: 2022-07-14 10:11:05.610824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f97a8a834e51'
down_revision = '4a1e7eb48df4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_results', 'result',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_results', 'result',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
